apiVersion: v1
kind: Service
metadata:
  name: rentalservice-service
spec:
  type: NodePort
  selector:
    app: rentalservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080